name: Build debug APK (JDK 17 + Gradle 7.5.1)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_VERSION: "7.5.1"
      GRADLE_DIST_URL: "https://services.gradle.org/distributions/gradle-7.5.1-bin.zip"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and unpack Gradle ${GRADLE_VERSION}
        shell: bash
        run: |
          mkdir -p $HOME/gradle
          curl -sSL "${{ env.GRADLE_DIST_URL }}" -o gradle.zip
          unzip -q gradle.zip -d $HOME/gradle
          rm gradle.zip
          GRADLE_BIN=$(ls -d $HOME/gradle/gradle-* | head -n1)/bin/gradle
          echo "GRADLE_BIN=$GRADLE_BIN" >> $GITHUB_ENV
          $GRADLE_BIN --version

      - name: Strip BOMs from gradle/properties (safety)
        shell: bash
        run: |
          find . -type f \( -name '*.gradle' -o -name '*.properties' \) -print0           | xargs -0 -n1 sed -i '1s/^\xEF\xBB\xBF//'

      - name: Choose gradle command (prefer wrapper if present)
        shell: bash
        run: |
          if [ -x "./gradlew" ]; then
            chmod +x ./gradlew
            echo "GRADLE_CMD=./gradlew" >> $GITHUB_ENV
          else
            echo "GRADLE_CMD=${GRADLE_BIN}" >> $GITHUB_ENV
          fi

      - name: Show java / gradle info
        shell: bash
        run: |
          java -version
          echo "Using gradle: $GRADLE_CMD"
          $GRADLE_CMD --version

      - name: Build debug APK
        shell: bash
        run: |
          set -o pipefail
          $GRADLE_CMD clean assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/*.apk
