name: Build debug APK (force Gradle 7.4.2)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_VERSION: "7.4.2"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SDKMAN and Gradle (specific)
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle $GRADLE_VERSION
          SDK_GRADLE="$HOME/.sdkman/candidates/gradle/$GRADLE_VERSION/bin/gradle"
          echo "SDK_GRADLE=$SDK_GRADLE" >> $GITHUB_ENV
          $SDK_GRADLE --version

      - name: Prefer project wrapper if present, else use SDKMAN gradle
        shell: bash
        run: |
          if [ -x "./gradlew" ]; then
            echo "Using project gradlew"
            chmod +x ./gradlew
            echo "GRADLE_CMD=./gradlew" >> $GITHUB_ENV
          else
            echo "Using SDKMAN gradle at $SDK_GRADLE"
            echo "GRADLE_CMD=$SDK_GRADLE" >> $GITHUB_ENV
          fi

      - name: Strip BOMs (safety)
        shell: bash
        run: |
          find . -type f \( -name '*.gradle' -o -name '*.properties' \) -print0 \
          | xargs -0 -n1 sed -i '1s/^\xEF\xBB\xBF//'

      - name: Build debug APK
        shell: bash
        run: |
          echo "Running: $GRADLE_CMD clean assembleDebug --no-daemon --stacktrace"
          $GRADLE_CMD clean assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/*.apk
