name: Build debug APK (use JDK 17)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SDKMAN and Gradle 7.4.2
        shell: bash
        run: |
          # install sdkman and a specific Gradle (if you want to use system gradle)
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 7.4.2
          gradle -v

      - name: Ensure Gradle wrapper preference
        shell: bash
        run: |
          # prefer ./gradlew if present, otherwise use system gradle
          if [ -x "./gradlew" ]; then
            echo "Using project gradlew"
            chmod +x ./gradlew
            export GRADLE_CMD="./gradlew"
          else
            echo "No gradlew found — using installed gradle"
            export GRADLE_CMD="gradle"
          fi
          echo "GRADLE_CMD=$GRADLE_CMD" >> $GITHUB_ENV

      - name: Strip BOMs from gradle/properties (safety)
        shell: bash
        run: |
          find . -type f \( -name '*.gradle' -o -name '*.properties' \) -print0 \
          | xargs -0 -n1 sed -i '1s/^\xEF\xBB\xBF//'

      - name: Build debug APK
        shell: bash
        run: |
          # use the selected gradle command
          $GRADLE_CMD clean assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/*.apk
